version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: restaurant-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: restaurant-backend
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"


  frontend:
    build: ./frontend
    container_name: restaurant-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data: